name: Run Gradle
on: 
  workflow_dispatch:
  push:
    branches: 
    - main
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew     
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.2

    - name: Execute Gradle build
      run: ./gradlew build -x test
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./build/libs/cicid1-*-SNAPSHOT.jar


  docker:
    needs: gradle
    runs-on: ubuntu-latest
    
  # unexpected status: 403 Forbidden
    permissions:
      contents: read
      packages: write
      
    steps :
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: my-artifact
            #root위치에서 down하므로 생략
            
#         - run : ls -ll

        - 
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}:latest
            
            
            
  deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sh deploy.sh

